services: 
  flowable-db:
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=internal
      - POSTGRES_DB=flowable
      - POSTGRES_USER=flowable
      - POSTGRES_PASSWORD=flowable
volumes:
  data_db: